apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgmes-gl-server
  labels:
    name: cgmes-gl-server
    version: "1"
spec:
  selector:
    matchLabels:
      name: cgmes-gl-server
  template:
    metadata:
      labels:
        name: cgmes-gl-server
    spec:
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      containers:
      - name: cgmes-gl
        image: docker.io/powsybl/cgmes-gl-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: cgmes-gl-server-configmap-volume
      restartPolicy: Always
      volumes:
        - name: cgmes-gl-server-configmap-volume
          configMap:
            name: cgmes-gl-server-configmap
